### ISSUE TITLE
Hello remember how you said unless uv is static space cant be static plss go to this link https://github.com/carbonnetwork-dev/Static-Proxy

### ISSUE THREAD

**Issue by 6huGt** [YUG38/YUG38#1]
https://github.com/carbonnetwork-dev/Static-Proxy

**Comment by YUG38** [comment]
Bro they aren't gonna change their whole code base to use static version of UV

**Comment by 6huGt** [comment]
They could just saying there are alot of static options out there and are
not limited by uv

**Comment by YUG38** [comment]
Ik and they know it too but everything has ups and downs so they prob don't wanna use static why you telling me about it, i am not the dev 😭😭

**Comment by 6huGt** [comment]
well you were the one that said oh they cant do it unless they modify uv well it already has bean modified

**Comment by YUG38** [comment]
Misclick and I said they modify the uv in their repo are you slow???

**Comment by 6huGt** [comment]
who in the world is misclick
